const icons = [
    'next-arrow',
    'logo',
    'smile',
    'mail',
    'phone',
    'popup-close',
    'file',
    'about-stats-1',
    'about-stats-2',
    'about-stats-3',
    'about-stats-4',
    'about-stats-5',
    'about-infinity',
    'services-adv-1',
    'services-adv-2',
    'services-adv-3',
    'services-adv-4',
    'services-adv-5',
    'services-adv-6',
    'services-adv-7',
    'services-adv-8',
] as const;

export default icons;
